export const {
  VITE_REGISTER_URL,
  VITE_LOGIN_URL,
  VITE_ADD_BURGER,
  VITE_GET_BURGERS,
  VITE_DELETE_BURGER,
  VITE_UPDATE_BURGER,
  VITE_CREATE_ORDER,
  VITE_GET_ORDERS,
  VITE_GET_ADMIN_ORDERS,
  VITE_CHANGE_STATUS,
} = import.meta.env;
